Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,8 +34,13 @@ jobs:
           git clean -fxd
 
       - name: Copy build output
-        run: |
-          cp -r dist/* .
+  run: |
+    if [ -d "dist" ]; then
+      cp -r dist/* .
+    else
+      echo "ERROR: dist/ folder not found"
+      exit 1
+    fi
 
       - name: Commit and push
         run: |
